### ISSUE TITLE
Add TypeScript declarations for window properties in playwright.fixtures.ts

### ISSUE THREAD

**Issue by natb1** [rumor-ml/commons.systems#1711]
## Problem
TypeScript compilation errors in `playwright.fixtures.ts` for window properties:
- `window.__TEST_COLLECTION_NAME__` (line 222)
- `window.auth` (multiple lines)
- `window.signInWithCustomToken` (lines 347, 356)
- `window.__testAuth` (lines 359, 388, 390, 391)
- Unknown error types (lines 290, 397)

## Context
These properties are set in Playwright init scripts for test fixtures but lack TypeScript type declarations.

## Impact
- Blocks `make typecheck` in CI for firebase apps (videobrowser, audiobrowser, fellspiral)
- Doesn't prevent tests from running
- Found during #1621 workflow run: https://github.com/rumor-ml/commons.systems/actions/runs/21547086841

## Solution
Add type declarations file (e.g., `playwright.d.ts`):
```typescript
declare global {
  interface Window {
    __TEST_COLLECTION_NAME__: string;
    auth: any; // TODO: Use proper Firebase Auth type
    signInWithCustomToken: (token: string) => Promise<any>;
    __testAuth: any;
  }
}
export {};
```

## Files Affected
- `playwright.fixtures.ts` (16 type errors)
- `videobrowser/tests/`
- `audiobrowser/tests/`
- `fellspiral/tests/`

## Related
- Discovered during #1621 workflow run
- Not caused by #1621 changes
